### ISSUE TITLE
re: Check if column start is greater than line length

### ISSUE THREAD

**Issue by joliveros** [AtomLinter/atom-linter#63] opened 2015-11-20 23:29 UTC
I'm currently getting
```
Error: Column start (11) greater than line length(8)
at Object.module.exports.Helpers.rangeFromLineNumber
lib/Helpers.coffee:73:17
```
while running atom-linter@3.3.7

related to pull request #53 ?

![](https://d1zjcuqflbd5k.cloudfront.net/files/acc_442812/kz4p?response-content-disposition=inline;%20filename=Screen%20Shot%20on%202015-11-20%20at%2017%3A15%3A24.png&Expires=1448085882&Signature=QhF-1ib7S9c~pK3vSvO-kwUG4UYqTIeuEzWV9fCZ3~TtrPI5KGMz1pTXBEQxQGr0NuPPYbF4NK39FHLdKKTOZH~ME5yjZZmRXkG0468~6fR1l6hd1hSnuUXMVK7mx4BRAjo-F177AwwWp-k2mo4m20cFL6kU3SlMSVTUogSJmnQ_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

**Comment by steelbrain** [comment] 2015-11-20 23:30
This is a bug in the provider, which provider are you using?

**Comment by joliveros** [comment] 2015-11-21 06:00
would that be `linter-eslint` ?
https://atom.io/packages/linter-eslint

**Comment by Arcanemagus** [comment] 2015-11-21 08:06
Possibly :stuck_out_tongue:

Do you have an example file that triggers this?

**Comment by joliveros** [comment] 2015-11-21 16:08
I get this on a lot of files, this is just one of them: https://gist.github.com/joliveros/88293359e810131184d2


—

**Comment by Arcanemagus** [comment] 2015-11-21 22:24
Can you post the related `.eslintrc`? I'm not seeing any issues with that file.

There are some debugging steps outlined here: https://github.com/AtomLinter/linter-php/issues/103#issuecomment-158475478
The info from there would help until I can reproduce this.

**Comment by joliveros** [comment] 2015-11-23 15:55
I'll go through the debugging steps. This is the .eslintrc file I'm using.
```
{
	"parser":	"babel-eslint",
	"plugins": [
		"babel"
	],
	"rules": {
		"strict":	0
	},
  "ecmaFeatures": {
    "arrowFunctions": true,
    "blockBindings": true,
    "generators": true,
    "templateStrings": true
  },
  "rules": {
    "strict": 0,
		"semi": [2, "always"],
    "no-underscore-dangle": 0,
    "no-unused-vars": 2,
    "curly": 0,
    "no-multi-spaces": 0,
    "key-spacing": 0,
    "no-return-assign": 0,
    "consistent-return": 0,
    "no-shadow": 0,
    "no-comma-dangle": 0,
    "no-use-before-define": 0,
    "no-empty": 0,
    "new-parens": 0,
    "no-cond-assign": 0,
    "camelcase": 0,
    "new-cap": [1, { "capIsNew": false }],
    "no-undef": 2,
		"babel/generator-star-spacing": 0,
    "babel/new-cap": 0,
    "babel/object-curly-spacing": 1,
    "babel/object-shorthand": 0,
    "babel/arrow-parens": 1
  },
  "env": {
    "node": true,
    "browser": true,
    "es6":true
  },
  "globals": {
    "IS_SERVER": true
  }
}

```

**Comment by Arcanemagus** [comment] 2015-11-23 17:55
Whoops, forgot to ask for the `package.json` to duplicate the environment. Mand putting that up as well? (Should only need the dependencies and devDependencies sections if the rest is sensitive)

**Comment by joliveros** [comment] 2015-11-23 17:59
```

{

  "name": "DSF",

  "version": "0.1.1",

  "private": true,

  "description": "starter",

  "main": "index.js",

  "dependencies": {

    "angular": "^1.4.6",

    "angular-animate": "^1.4.6",

    "angular-bootstrap-npm": "^0.13.4",

    "angular-cookies": "^1.4.3",

    "angular-debounce": "^1.0.3",

    "angular-jwt": "0.0.9",

    "angular-loading-bar": "^0.8.0",

    "angular-route": "^1.4.3",

    "angular-sanitize": "^1.4.3",

    "angular-ui-event": "~1.0.0",

    "angular-ui-mask": "~1.4.6",

    "angular-ui-router": "~0.2.15",

    "angular-xeditable": "0.0.1",

    "angularjs-toaster": "*",

    "babel-runtime": "^5.8.25",

    "blueimp-file-upload": "^9.11.2",

    "blueimp-gallery": "^2.16.0",

    "bootstrap": "^3.3.5",

    "bower": "^1.6.5",

    "debug": "^2.2.0",

    "flexslider": "^2.5.0",

    "fs": "0.0.2",

    "highcharts-ng": "^0.0.11",

    "jquery": "^2.1.1",

    "jquery-slimscroll": "^1.3.6",

    "jquery-ui": "^1.10.5",

    "json-loader": "^0.5.3",

    "lodash": "^3.8.0",

    "moment": "^2.10.6",

    "moment-timezone": "^0.4.1",

    "ngstorage": "*",

    "node-restangular": "^0.1.0",

    "oclazyload": "1.0.6",

    "qs": "^6.0.0",

    "restangular": "^1.5.1",

    "ui-router-extras": "^0.1.0",

    "validator": "^4.2.1"

  },

  "devDependencies": {

    "angular-mocks": "^1.3.15",

    "babel-core": "^5.4.2",

    "babel-loader": "^5.0.0",

    "babel-plugin-node-env-inline": "^1.0.1",

    "bootstrap-webpack": "0.0.3",

    "clean-webpack-plugin": "*",

    "compass-mixins": "*",

    "compression-webpack-plugin": "^0.2.0",

    "connect-modrewrite": "^0.8.1",

    "cors": "^2.7.1",

    "css-loader": "^0.12.1",

    "del": "^2.0.2",

    "expose-loader": "^0.7.0",

    "extract-text-webpack-plugin": "^0.8.2",

    "file-loader": "^0.8.4",

    "fs-walk": "0.0.1",

    "globals-loader": "*",

    "gulp": "^3.8.11",

    "gulp-debug": "^2.1.2",

    "gulp-deploy-azure-cdn": "^2.0.0",

    "gulp-load-plugins": "^0.10.0",

    "gulp-ng-constant": "^0.3.0",

    "gulp-rename": "^1.2.2",

    "gulp-replace": "^0.5.4",

    "gulp-rimraf": "^0.2.0",

    "gulp-template": "^3.0.0",

    "gulp-util": "^3.0.6",

    "html-loader": "^0.3.0",

    "html-webpack-plugin": "^1.6.1",

    "image-webpack-loader": "^1.6.1",

    "imagemin": "^3.2.0",

    "imports-loader": "^0.6.4",

    "karma": "^0.12.31",

    "karma-chai": "^0.1.0",

    "karma-chrome-launcher": "^0.1.12",

    "karma-mocha": "^0.1.10",

    "karma-mocha-reporter": "^1.0.2",

    "karma-sourcemap-loader": "^0.3.4",

    "karma-webpack": "^1.5.1",

    "mocha": "^2.2.5",

    "ng-annotate-webpack-plugin": "^0.1.2",

    "node-libs-browser": "^0.5.0",

    "node-sass": "^3.2.0",

    "node-storage": "0.0.7",

    "path": "^0.11.14",

    "raw-loader": "^0.5.1",

    "run-sequence": "^1.1.0",

    "sass-loader": "^1.0.2",

    "script-loader": "^0.6.1",

    "stats-webpack-plugin": "^0.2.2",

    "style-loader": "^0.12.2",

    "url-loader": "^0.5.6",

    "webpack": "^1.12.1",

    "webpack-dev-server": "^1.12.1",

    "webpack-manifest-plugin": "^0.4.0",

    "webpack-stream": "^2.0.0",

    "yargs": "^3.9.0"

  },

  "scripts": {

    "install": "node_modules/.bin/bower install",

    "test": "karma start"

  },

  "keywords": [

    "angular",

    "webpack",

    "es6"

  ]

}



```

Thank you!


—

**Comment by Arcanemagus** [comment] 2015-11-23 18:00
Was able to reproduce it, investigating!

**Comment by Arcanemagus** [comment] 2015-11-23 18:07
So the issue is that you are mixing indentation styles throughout the file. The way we are currently calculating the start of the line's content is taking the number of indentations reported by Atom _for that line_ and multiplying by the indentation size _for the file_.

Looks like we need to figure out a better way of determining the start of the line's content since Atom has no function to get the "indentation length" for a single line, only the file level.

**Comment by joliveros** [comment] 2015-11-23 18:10
Ok, I think I can make it work. Thank you!


—

**Comment by Arcanemagus** [comment] 2015-11-23 18:11
Yea, fixing this on your end should be as simple as making the indentation style standard across the whole file. Working on a robust fix for this for all files that will be released for everyone :wink:.

**Closed** 2015-11-23 19:47 UTC

**Comment by Arcanemagus** [comment] 2015-11-23 19:52
Pushed out v3.3.8 of this which should fix things, will be releasing versions of the linters this was reported on that require it soon.

**Comment by BlaM** [comment] 2015-11-26 07:42
Just want to add a quick "Thank You". Atom-Linter is one of the reasons why I got stuck with Atom :+1:

**Comment by Arcanemagus** [comment] 2015-11-28 03:26
Actually the reason I picked Atom also was the linter integration from the very beginning :wink:, Sublime had a terrible UI for that back then.
